require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChambersController do

  # This should return the minimal set of attributes required to create a valid
  # Chamber. As you add validations to Chamber, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { name: "MyString", description: "My Description" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChambersController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  let(:user) { FactoryGirl.create(:user) }

  describe "GET index" do
    it "assigns all chambers as @chambers" do
      chamber = Chamber.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chambers).should eq([chamber])
    end
  end

  describe "GET show" do
    it "assigns the requested chamber as @chamber" do
      chamber = Chamber.create! valid_attributes
      get :show, {:id => chamber.to_param}, valid_session
      assigns(:chamber).should eq(chamber)
    end
  end

  describe "GET new" do
    before do 
      sign_in user, no_capybara: true
    end

    it "assigns a new chamber as @chamber" do
      get :new, {}, valid_session
      assigns(:chamber).should be_a_new(Chamber)
    end
  end

  describe "GET edit" do
    before do 
      sign_in user, no_capybara: true
    end

    it "assigns the requested chamber as @chamber" do
      chamber = Chamber.create! valid_attributes
      get :edit, {:id => chamber.to_param}, valid_session
      assigns(:chamber).should eq(chamber)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      before do 
        sign_in user, no_capybara: true
      end

      it "creates a new Chamber" do
        expect {
          post :create, {:chamber => valid_attributes}, valid_session
        }.to change(Chamber, :count).by(1)
      end

      it "assigns a newly created chamber as @chamber" do
        post :create, {:chamber => valid_attributes}, valid_session
        assigns(:chamber).should be_a(Chamber)
        assigns(:chamber).should be_persisted
      end

      it "redirects to the created chamber" do
        post :create, {:chamber => valid_attributes}, valid_session
        response.should redirect_to(Chamber.last)
      end
    end

    describe "with invalid params" do
      before { sign_in user, no_capybara: true}

      it "assigns a newly created but unsaved chamber as @chamber" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chamber.any_instance.stub(:save).and_return(false)
        post :create, {:chamber => { "name" => "invalid value" }}, valid_session
        assigns(:chamber).should be_a_new(Chamber)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chamber.any_instance.stub(:save).and_return(false)
        post :create, {:chamber => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      before { sign_in user, no_capybara: true}

      it "updates the requested chamber" do
        chamber = Chamber.create! valid_attributes
        # Assuming there are no other chambers in the database, this
        # specifies that the Chamber created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chamber.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => chamber.to_param, :chamber => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested chamber as @chamber" do
        chamber = Chamber.create! valid_attributes
        put :update, {:id => chamber.to_param, :chamber => valid_attributes}, valid_session
        assigns(:chamber).should eq(chamber)
      end

      it "redirects to the chamber" do
        chamber = Chamber.create! valid_attributes
        put :update, {:id => chamber.to_param, :chamber => valid_attributes}, valid_session
        response.should redirect_to(chamber)
      end
    end

    describe "with invalid params" do
      before { sign_in user, no_capybara: true}
      it "assigns the chamber as @chamber" do
        chamber = Chamber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chamber.any_instance.stub(:save).and_return(false)
        put :update, {:id => chamber.to_param, :chamber => { "name" => "invalid value" }}, valid_session
        assigns(:chamber).should eq(chamber)
      end

      it "re-renders the 'edit' template" do
        chamber = Chamber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chamber.any_instance.stub(:save).and_return(false)
        put :update, {:id => chamber.to_param, :chamber => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    before { sign_in user, no_capybara: true}

    it "destroys the requested chamber" do
      chamber = Chamber.create! valid_attributes
      expect {
        delete :destroy, {:id => chamber.to_param}, valid_session
      }.to change(Chamber, :count).by(-1)
    end

    it "redirects to the chambers list" do
      chamber = Chamber.create! valid_attributes
      delete :destroy, {:id => chamber.to_param}, valid_session
      response.should redirect_to(chambers_url)
    end
  end

end
